routes/web.php
<?php

declare(strict_types=1);

use Bittacora\Bpanel4\Contact\Http\Controllers\ContactAdminController;
use Bittacora\Bpanel4\Contact\Http\Controllers\ContactPublicController;
use Illuminate\Support\Facades\Route;

Route::middleware(['web'])->group(function () {
    Route::get('/contacto', [ContactPublicController::class, 'index'])->name('contact');
    Route::post('/contacto', [ContactPublicController::class, 'send'])->name('send-contact');
});


Route::prefix('bpanel/contacto')->name('contact-admin.')->middleware(['web', 'auth', 'admin-menu'])
    ->group(static function () {
        Route::get('/editar', [ContactAdminController::class, 'edit'])->name('edit');
        Route::put('/editar', [ContactAdminController::class, 'update'])->name('update');
        Route::get('/listar', [ContactAdminController::class, 'index'])->name('index');
        Route::get('/ver/{submission}', [ContactAdminController::class, 'show'])->name('show');
        Route::delete('/eliminar/{submission}', [ContactAdminController::class, 'destroy'])->name('destroy');
    });

resources/views/bpanel/edit.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Editar detalles de contacto')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">Editar detalles de contacto</span>
            </h4>
        </div>
        <form class="mt-lg-3" autocomplete="off" method="post" action="{{route('contact-admin.update')}}">
            @method('PUT')
            @csrf
            @if($errors->any())
                {!! implode('', $errors->all('<div>:message</div>')) !!}
            @endif

            @livewire('utils::tinymce-editor', ['name' => 'introductory_text', 'labelText' => __('bpanel4-contact::contact_info.introductory_text'), 'value' => old('introductory_text') ?? $contactInfo->introductory_text ])
            @livewire('utils::tinymce-editor', ['name' => 'contact_details', 'labelText' => __('bpanel4-contact::contact_info.contact_details'), 'value' => old('contact_details') ?? $contactInfo->contact_details ])

            <x-bpanel4-map-input name="location" description="Haga click en el mapa para establecer la ubicación que se mostrará en la página de contacto." :latitude="$contactInfo->latitude" :longitude="$contactInfo->longitude" :zoom="$contactInfo->zoom"/>

            <div class="col-12 mt-5 border-t-1 bgc-secondary-l4 brc-secondary-l2 py-35 d-flex justify-content-center">
                @livewire('form::save-button',['theme'=>'update'])
                @livewire('form::save-button',['theme'=>'reset'])
            </div>
        </form>
    </div>

@endsection

resources/views/bpanel/index.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Contacto')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-contact::datatable.index') }}</span>
            </h4>
        </div>
        <div class="card-body">
            @livewire('bpanel4-contact::livewire.submissions-table', [], key('bpanel4-contact-table'))
        </div>
    </div>


@endsection

resources/views/bpanel/livewire/datatable-columns/actions.blade.php
@livewire('utils::datatable-action-buttons', ['actions' => ["show", "delete"], 'scope' => 'contact-admin', 'model' => $row, 'permission' => ['show', 'delete'], 'id' => $row->id, 'message' => 'el mensaje?'], key('user-buttons-'.$row->id))

resources/views/bpanel/livewire/submissions-datatable.blade.php
<td>
    {{ date_format($row->created_at, 'd-m-Y H:i') }}
</td>
<td>
    {{ $row->name }}
</td>
<td>
    {{ $row->email }}
</td>
<td>
    {{ $row->phone }}
</td>
<td>
    {{ substr(strip_tags($row->message), 0, 120) }} @if (strlen(strip_tags($row->message)) > 120)...@endif
</td>
<td class="text-center">
    <a href="{{ route('contact-admin.show', ['submission' => $row->id]) }}"><i class="fa fa-eye"></i></a>
    <form method="POST" class="d-inline mx-2"
          action="{{route('contact-admin.destroy', ['submission' => $row->id])}}">
        {!!method_field('DELETE')!!}
        @csrf
        <button id="delete_button{{$row->id}}" type="submit" class="btn btn-primary-outline text-danger"
                onclick="return confirm('¿Está seguro de querer borrar este mensaje?')">
            <i class="fa fa-trash"></i>
        </button>
    </form>
</td>

resources/views/bpanel/show.blade.php
@extends('bpanel4::layouts.bpanel-app')

@section('title', 'Contacto')

@section('content')
    <div class="card bcard">
        <div class="card-header bgc-primary-d1 text-white border-0">
            <h4 class="text-120 mb-0">
                <span class="text-90">{{ __('bpanel4-contact::datatable.show') }}</span>
            </h4>
        </div>
        <div class="card-body">
            <table>
                <tr>
                    <th class="pb-2 pr-2">Hora de envío:</th>
                    <td class="pb-2">{{ date_format($submission->created_at, 'd-m-Y H:i:s') }}</td>
                </tr>
                <tr>
                    <th class="pb-2 pr-2">Nombre:</th>
                    <td class="pb-2">{{ $submission->name }}</td>
                </tr>
                <tr>
                    <th class="pb-2 pr-2">Email:</th>
                    <td class="pb-2">{{ $submission->email }}</td>
                </tr>
                <tr>
                    <th class="pb-2 pr-2">Teléfono:</th>
                    <td class="pb-2">{{ $submission->phone }}</td>
                </tr>
                <tr>
                    <th class="pb-2 pr-2" style="vertical-align: top">Mensaje:</th>
                    <td class="pb-2">{!! nl2br(strip_tags($submission->message)) !!}</td>
                </tr>
            </table>
        </div>
    </div>


@endsection

resources/views/form.blade.php
@extends('bpanel4-public.layouts.regular-page')
@section('title')
    Contacto
@endsection
@livewireStyles
@section('content')
    <div>
        <h1>Contacto</h1>
        {{--
        Con el siguiente código se pueden mostrar los campos que se configuran desde el panel. No los incluyo en la
        vista de ejemplo.
        {!! $contactDetails->introductory_text !!}
        {!! $contactDetails->contact_details !!}
        <x-bpanel4-map :latitude="$contactDetails->latitude" :longitude="$contactDetails->longitude" :zoom="$contactDetails->zoom" name="contact_map"/>
        --}}
        <div>
            <form class="bpanel4-contact-form" method="post" action="{{ route('send-contact') }}">
                <input name="name" type="text" maxlength="255" placeholder="Nombre y apellidos" class="name">
                <div class="contact-details">
                    <input type="email" name="email" maxlength="255" placeholder="Correo electrónico">
                    <input type="tel" name="phone" placeholder="Teléfono">
                </div>
                <textarea name="message"
                          placeholder="Escriba su duda o consulta de forma breve, le responderemos lo antes posible."></textarea>
                <div class="acceptance">
                    <label><input type="checkbox" name="acceptance" value="1" required> Confirmo que he leído la información básica sobre protección de datos y la política de privacidad y autorizo el registro de mis datos para los fines indicados.</label>
                </div>
                <div class="recaptcha">
                    {!! NoCaptcha::display() !!}
                @if (isset($errors) && $errors->has('g-recaptcha-response'))
                        <span class="help-block">
                            <strong>{{ $errors->first('g-recaptcha-response') }}</strong>
                        </span>
                    @endif
                </div>
                <div>
                    <button type="submit">Enviar</button>
                </div>
                @csrf
            </form>
        </div>
    </div>
@endsection
@livewireScripts
{!! NoCaptcha::renderJs() !!}